const data = {
  product: [
    {
      productNumber: 1001,
      name: 'Dewalt 20V Cordless Drill',
      slug: 'dewalt-20v-cordless-drill',
      category: 'Power Tools',
      image: '/images/p1.jpeg',
      price: 149.99,
      countInStock: 25,
      brand: 'Dewalt',
      rating: 4.8,
      numReviews: 500,
      Description:
        'The Dewalt 20V Cordless Drill is a powerful and versatile tool for any DIY or professional project. With a 20V lithium-ion battery, this drill offers plenty of power and a long-lasting charge.',
    },
    {
      productNumber: 1002,
      name: 'Milwaukee M18 Cordless Impact Wrench',
      slug: 'milwaukee-m18-cordless-impact-wrench',
      category: 'Power Tools',
      image: '/images/p2.jpeg',
      price: 199.99,
      countInStock: 15,
      brand: 'Milwaukee',
      rating: 4.9,
      numReviews: 300,
      description:
        'The Milwaukee M18 Cordless Impact Wrench is a powerful and durable tool for heavy-duty projects. With a M18 lithium-ion battery, this impact wrench offers maximum power and a long-lasting charge.',
    },
    {
      productNumber: 1003,
      name: 'Kreg Jig K5 Pocket Hole System',
      slug: 'kreg-jig-k5-pocket-hole-system',
      category: 'Woodworking Tools',
      image: '/images/p3.jpeg',
      price: 129.99,
      countInStock: 20,
      brand: 'Kreg',
      rating: 4.7,
      numReviews: 400,
      description:
        'The Kreg Jig K5 Pocket Hole System is a versatile and easy-to-use tool for any woodworking project. With its durable construction and simple design, this pocket hole system makes it easy to create strong, secure joints.',
    },

    {
      productNumber: 1004,
      name: 'Bosch 10-Inch Table Saw',
      slug: 'bosch-10-inch-table-saw',
      category: 'Power Tools',
      image: '/images/p4.jpeg',
      price: 499.99,
      countInStock: 10,
      brand: 'Bosch',
      rating: 4.9,
      numReviews: 200,
      description:
        'The Bosch 10-Inch Table Saw is a powerful and precise tool for any woodworking project. With its durable construction and accurate cutting capabilities, this table saw is perfect for professional or DIY use.',
    },
    {
      productNumber: 1005,
      name: 'Kobalt 40-Piece Standard Tool Set',
      slug: 'kobalt-40-piece-standard-tool-set',
      category: 'Hand Tools',
      image: '/images/p5.jpeg',
      price: 49.99,
      countInStock: 10,
      brand: 'Kobalt',
      rating: 4.6,
      numReviews: 62,
      description:
        "The Kobalt 40-Piece Standard (SAE) and Metric Mechanic's Tool Set is a comprehensive collection of tools that is perfect for mechanics and DIY enthusiasts. It includes a variety of sockets, wrenches, pliers, and screwdrivers in both standard and metric sizes.",
    },
    {
      productNumber: 1006,
      name: 'Milwaukee M18 Cordless Hammer Drill',
      slug: 'milwaukee-m18-cordless-hammer-drill',
      category: 'Power Tools',
      image: '/images/p6.jpeg',
      price: 399.99,
      countInStock: 5,
      brand: 'Milwaukee',
      rating: 4.9,
      numReviews: 36,
      description:
        'The Milwaukee M18 FUEL 18-Volt Lithium-Ion Brushless Cordless Hammer Drill/Impact Driver Combo Kit is a powerful and versatile tool set that is perfect for a wide range of drilling and driving applications. It features a high-performance brushless motor and a compact, lightweight design for easy maneuverability and control.',
    },
    {
      productNumber: 1007,
      name: 'Bosch Jigsaw JS470E',
      slug: 'bosch-jigsaw-js470e',
      category: 'Power Tools',
      image: '/images/p7.jpeg',
      price: 99.99,
      countInStock: 25,
      brand: 'Bosch',
      rating: 4.5,
      numReviews: 30,
      description:
        'The Bosch Jigsaw JS470E is a powerful and versatile tool for cutting a variety of materials. It features a precision guidance system for straight cuts and a comfortable grip for extended use.',
    },
    {
      productNumber: 1008,
      name: 'Kwikset Smart Lock',
      slug: 'kwikset-smart-lock',
      category: 'Home Security',
      image: '/images/p8.jpeg',
      price: 199.99,
      countInStock: 10,
      brand: 'Kwikset',
      rating: 4.7,
      numReviews: 15,
      description:
        'The Kwikset Smart Lock is a convenient and secure way to control access to your home. It can be controlled with a smartphone app and features customizable access codes for guests.',
    },
    {
      productNumber: 1009,
      name: 'Behr Premium Plus Ultra Paint',
      slug: 'behr-premium-plus-ultra-paint',
      category: 'Painting Supplies',
      image: '/images/p9.jpg',
      price: 34.99,
      countInStock: 50,
      brand: 'Behr',
      rating: 4.6,
      numReviews: 20,
      description:
        'Behr Premium Plus Ultra Paint is a high-quality, self-priming paint that provides excellent coverage and durability. It is suitable for both indoor and outdoor use and comes in a variety of colors.',
    },
    {
      productNumber: 1010,
      name: 'TOTO Drake II Toilet',
      slug: 'toto-drake-ii-toilet',
      category: 'Plumbing',
      image: '/images/p10.jpeg',
      price: 269.99,
      countInStock: 15,
      brand: 'TOTO',
      rating: 4.8,
      numReviews: 25,
      description:
        'The TOTO Drake II Toilet is a sleek and powerful toilet that features a powerful flush system and an elongated bowl for added comfort.',
    },
    {
      productNumber: 1011,
      name: 'Makita 18V LXT Cordless Impact Driver',
      slug: 'makita-18v-lxt-cordless-impact-driver',
      category: 'Power Tools',
      image: '/images/p11.jpeg',
      price: 139.99,
      countInStock: 20,
      brand: 'Makita',
      rating: 4.7,
      numReviews: 35,
      description:
        'The Makita 18V LXT Cordless Impact Driver is a powerful and versatile tool that is perfect for driving large screws and bolts. It has a comfortable grip and a range of adjustable settings for precision and control.',
    },
  ],
};

export default data;
