import bcrypt from 'bcryptjs';

const data = {
  products: [
    {
      name: 'HomePointe 18 inch Oscillating Stand Fan',
      slug: 'homepointe-18-inch-oscillating-stand-fan',
      department: 'Outdoor & Patio',
      image: '/images/p1.png',
      price: 18.99,
      countInStock: 0,
      brand: 'HomePointe',
      rating: 3.8,
      numReviews: 12,
      description:
        'The HomePointe 18 inch Oscillating Stand Fan is a top-of-the-line electric fan that delivers powerful, yet quiet, cooling to any room in your home or office. With its oscillating head, it circulates air evenly throughout the space, ensuring that every corner stays cool and comfortable.At 18 inches in blade diameter, this fan provides ample air flow while still fitting neatly in any room. It is easy to adjust the height of the fan to suit your needs, and the adjustable speed settings let you customize the intensity of the breeze to your liking. The fan is also equipped with a tilt-adjustable head, allowing you to direct the air flow exactly where you need it. This fan is the perfect solution for hot and stuffy summer days, and it is also great for year-round air circulation. It is built with a durable and energy-efficient motor, and its quiet operation will not disturb you or your guests. ',
    },
    {
      name: 'PikStick Pro All Purpose Stick',
      slug: 'pikstick-pro-all-purpose-stick',
      department: 'Outdoor & Patio',
      image: '/images/p2.png',
      price: 12.99,
      countInStock: 15,
      brand: 'PikStick',
      rating: 3.2,
      numReviews: 8,
      description:
        'The Milwaukee M18 Cordless Impact Wrench is a powerful and durable tool for heavy-duty projects. With a M18 lithium-ion battery, this impact wrench offers maximum power and a long-lasting charge.',
    },
    {
      name: 'Globe 48ft LED String Lights',
      slug: 'globe-48ft-led-string-lights',
      department: 'Lighting',
      image: '/images/p3.png',
      price: 79.99,
      countInStock: 9,
      brand: 'Globe',
      rating: 4.7,
      numReviews: 18,
      description:
        'The Kreg Jig K5 Pocket Hole System is a versatile and easy-to-use tool for any woodworking project. With its durable construction and simple design, this pocket hole system makes it easy to create strong, secure joints.',
    },

    {
      name: 'Vintage Style 60W Warm Candle Light',
      slug: 'vintage-style-60w-warm-candle-light',
      department: 'Lighting',
      image: '/images/p4.png',
      price: 24.99,
      countInStock: 10,
      brand: 'Vintage',
      rating: 4.9,
      numReviews: 11,
      description:
        'The Bosch 10-Inch Table Saw is a powerful and precise tool for any woodworking project. With its durable construction and accurate cutting capabilities, this table saw is perfect for professional or DIY use.',
    },
    {
      name: '1/3 HP Master Plumber Submersible Sump Pump',
      slug: '1/3-hp-master-plumber-submersible-sump-pump',
      department: 'Plumbing',
      image: '/images/p5.png',
      price: 99.99,
      countInStock: 10,
      brand: 'Master Olumber',
      rating: 4.6,
      numReviews: 3,
      description:
        "The Kobalt 40-Piece Standard (SAE) and Metric Mechanic's Tool Set is a comprehensive collection of tools that is perfect for mechanics and DIY enthusiasts. It includes a variety of sockets, wrenches, pliers, and screwdrivers in both standard and metric sizes.",
    },
    {
      name: 'Moen 6 Settings Magnetix Shower Head',
      slug: 'moen-6-settings-magnetix-shower-head',
      department: 'Plumbing',
      image: '/images/p6.png',
      price: 29.99,
      countInStock: 5,
      brand: 'Moen',
      rating: 5,
      numReviews: 9,
      description:
        'The Milwaukee M18 FUEL 18-Volt Lithium-Ion Brushless Cordless Hammer Drill/Impact Driver Combo Kit is a powerful and versatile tool set that is perfect for a wide range of drilling and driving applications. It features a high-performance brushless motor and a compact, lightweight design for easy maneuverability and control.',
    },
    {
      name: 'EZ-T Tint Base Easy Care Eggshell Interior Paint',
      slug: 'ez-t-tint-base-easy-care-eggshell-interior-paint',
      department: 'Paint',
      image: '/images/p7.png',
      price: 34.99,
      countInStock: 25,
      brand: 'Easy Care',
      rating: 4.2,
      numReviews: 30,
      description:
        'The Bosch Jigsaw JS470E is a powerful and versatile tool for cutting a variety of materials. It features a precision guidance system for straight cuts and a comfortable grip for extended use.',
    },
    {
      name: 'EZS-P Pure White Easy Care Semi-Gloss Interior Paint',
      slug: 'ezs-p-pure-white-easy-care-semi-gloss-interior-paint',
      department: 'Paint',
      image: '/images/p8.png',
      price: 34.99,
      countInStock: 10,
      brand: 'Easy Care',
      rating: 4.7,
      numReviews: 15,
      description:
        'The Kwikset Smart Lock is a convenient and secure way to control access to your home. It can be controlled with a smartphone app and features customizable access codes for guests.',
    },
    {
      name: 'SHP-P Pure White Easy Care Satin Exterior Paint',
      slug: 'shp-p-pure-white-easy-care-satin-exterior-paint',
      department: 'Paint',
      image: '/images/p9.png',
      price: 34.99,
      countInStock: 19,
      brand: 'Easy Care',
      rating: 4.6,
      numReviews: 16,
      description:
        'Behr Premium Plus Ultra Paint is a high-quality, self-priming paint that provides excellent coverage and durability. It is suitable for both indoor and outdoor use and comes in a variety of colors.',
    },
    {
      name: 'HPX-N Neutral Base Easy Care Flat Exterior Paint',
      slug: 'hpx-n-neutral-base-easy-care-flat-exterior-paint',
      department: 'Paint',
      image: '/images/p10.png',
      price: 34.99,
      countInStock: 15,
      brand: 'Easy Care',
      rating: 4.8,
      numReviews: 12,
      description:
        'The TOTO Drake II Toilet is a sleek and powerful toilet that features a powerful flush system and an elongated bowl for added comfort.',
    },
    {
      name: '50ft Green Thumb Light Weight Water Hose',
      slug: '50ft-green-thumb-light-weight-water-hose',
      department: 'Outdoor & Patio',
      image: '/images/p11.png',
      price: 54.99,
      countInStock: 6,
      brand: 'Green Thumb',
      rating: 3.7,
      numReviews: 7,
      description:
        'The Makita 18V LXT Cordless Impact Driver is a powerful and versatile tool that is perfect for driving large screws and bolts. It has a comfortable grip and a range of adjustable settings for precision and control.',
    },
    {
      name: 'Scotts Zoysia Grass Seed and Mulch ',
      slug: 'scotts-zoysia-grass-seed-and-mulch',
      department: 'Lawn & Garden',
      image: '/images/p12.png',
      price: 14.99,
      countInStock: 13,
      brand: 'Scotts',
      rating: 4.8,
      numReviews: 9,
      description:
        'The Dewalt 20V Cordless Drill is a powerful and versatile tool for any DIY or professional project. With a 20V lithium-ion battery, this drill offers plenty of power and a long-lasting charge.',
    },
    {
      name: 'Scotts Elite Spreader Wheelbarrow ',
      slug: 'scotts-elite-spreader-wheel-barrow',
      department: 'Lawn & Garden',
      image: '/images/p13.png',
      price: 49.99,
      countInStock: 8,
      brand: 'Scotts',
      rating: 4.1,
      numReviews: 16,
      description:
        'The Dewalt 20V Cordless Drill is a powerful and versatile tool for any DIY or professional project. With a 20V lithium-ion battery, this drill offers plenty of power and a long-lasting charge.',
    },
    {
      name: 'Drano Max Gel Clog Remover ',
      slug: 'drano-max-gel-clog-remover',
      department: 'Plumbing',
      image: '/images/p14.png',
      price: 19.99,
      countInStock: 25,
      brand: 'Drano',
      rating: 4.8,
      numReviews: 12,
      description:
        'The Dewalt 20V Cordless Drill is a powerful and versatile tool for any DIY or professional project. With a 20V lithium-ion battery, this drill offers plenty of power and a long-lasting charge.',
    },
    {
      name: 'Stanley 10pc Screwdriver Set ',
      slug: 'stanley-10pc-screwdriver-set',
      department: 'Tools',
      image: '/images/p15.png',
      price: 29.99,
      countInStock: 8,
      brand: 'Stanley',
      rating: 4.5,
      numReviews: 22,
      description:
        'The Dewalt 20V Cordless Drill is a powerful and versatile tool for any DIY or professional project. With a 20V lithium-ion battery, this drill offers plenty of power and a long-lasting charge.',
    },
    {
      name: 'Dewalt 168pc Mechanic Tool Set',
      slug: 'dewalt-168pc-mechanic-tool-set',
      department: 'Tools',
      image: '/images/p16.png',
      price: 209.99,
      countInStock: 2,
      brand: 'Dewalt',
      rating: 4.4,
      numReviews: 6,
      description:
        'The Dewalt 20V Cordless Drill is a powerful and versatile tool for any DIY or professional project. With a 20V lithium-ion battery, this drill offers plenty of power and a long-lasting charge.',
    },
    {
      name: 'Vacmaster Pro Series Wet/Dry Vacuum 12 Gallons',
      slug: 'vacmaster-pro-series-wet-dry-vacuum-12-gallons',
      department: 'Tools',
      image: '/images/p17.png',
      price: 149.99,
      countInStock: 3,
      brand: 'Vacmaster',
      rating: 5,
      numReviews: 2,
      description:
        'The Dewalt 20V Cordless Drill is a powerful and versatile tool for any DIY or professional project. With a 20V lithium-ion battery, this drill offers plenty of power and a long-lasting charge.',
    },
    {
      name: 'Dewalt 12V Extreme Cordless Drill/Driver Kit ',
      slug: 'dewalt-12v-extreme-cordless-drill-driver-kit',
      department: 'Tools',
      image: '/images/p18.png',
      price: 149.99,
      countInStock: 8,
      brand: 'Dewalt',
      rating: 4.8,
      numReviews: 27,
      description:
        'The Dewalt 20V Cordless Drill is a powerful and versatile tool for any DIY or professional project. With a 20V lithium-ion battery, this drill offers plenty of power and a long-lasting charge.',
    },
    {
      name: 'Dewalt 20V Impact Brushless Driver Kit',
      slug: 'dewalt-20v-impact-brushless-driver-kit',
      department: 'Tools',
      image: '/images/p19.png',
      price: 119.99,
      countInStock: 10,
      brand: 'Dewalt',
      rating: 4.8,
      numReviews: 18,
      description:
        'The Dewalt 20V Cordless Drill is a powerful and versatile tool for any DIY or professional project. With a 20V lithium-ion battery, this drill offers plenty of power and a long-lasting charge.',
    },
    {
      name: 'Dewalt 60V 17" String Trimmer',
      slug: 'dewalt-60V-17"-string-trimmer',
      department: 'Power Tools',
      image: '/images/p20.png',
      price: 249.99,
      countInStock: 6,
      brand: 'Dewalt',
      rating: 4.1,
      numReviews: 11,
      description:
        'The Dewalt 20V Cordless Drill is a powerful and versatile tool for any DIY or professional project. With a 20V lithium-ion battery, this drill offers plenty of power and a long-lasting charge.',
    },
    {
      name: 'Dewalt 60V Handheld Blower',
      slug: 'dewalt-60v-handheld-blower',
      department: 'Power Tools',
      image: '/images/p21.png',
      price: 189.99,
      countInStock: 8,
      brand: 'Dewalt',
      rating: 4.6,
      numReviews: 15,
      description:
        'The Dewalt 20V Cordless Drill is a powerful and versatile tool for any DIY or professional project. With a 20V lithium-ion battery, this drill offers plenty of power and a long-lasting charge.',
    },
  ],

  users: [
    {
      name: 'BTVH',
      email: 'btvh@owner.com',
      password: bcrypt.hashSync('btvh1234'),
      isAdmin: true,
    },
    {
      name: 'User',
      email: 'user@customer.com',
      password: bcrypt.hashSync('user1234'),
      isAdmin: false,
    },
  ],
};

export default data;
